plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
markdown: GFM
highlighter: rouge
include:
  - README.md
  - LICENSE.txt
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
